repos:
  - repo: https://github.com/Trim21/pre-commit-hooks
    rev: c37e29c1e823c5ce25cac879a0aa7fd63d387c25  # frozen: v0.0.1
    hooks:
      - id: yamlfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ebc15addedad713c86ef18ae9632c88e187dd0af  # frozen: v3.1.0
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-added-large-files  # check for file bigger than 500kb
      - id: debug-statements
      - id: trailing-whitespace
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: pretty-format-json
        args: [--no-ensure-ascii, --no-sort-keys, --indent, '2', --autofix]
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/Trim21/find-trailing-comma
    rev: 6f7daa24655f33876ae870aa8ad808639693d775  # frozen: v0.0.1
    hooks:
      - id: find-trailing-comma

  - repo: https://github.com/asottile/pyupgrade
    rev: 4656fbe8173b927bc215d09db1af0ef739741ad0  # frozen: v2.5.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/PyCQA/doc8
    rev: 0ef8e5665926edac4f9f86a98891b963c33a702a  # frozen: 0.8.1rc3
    hooks:
      - id: doc8
        args: [--max-line-length, '88', --file-encoding, utf-8]

  - repo: https://github.com/Trim21/poetry-check-lock
    rev: 63621580c70f106fd07748c262b6e08fef886ecc  # frozen: v0.0.3
    hooks:
      - id: poetry-check-lock

  - repo: https://github.com/timothycrosley/isort
    rev: cd9c2f6e70196bd429d0179635e0fac2d034ac5e  # frozen: 4.3.21-2
    hooks:
      - id: isort

  - repo: https://github.com/Trim21/mirrors-autoflake
    rev: b8c878d1121dc5160be52479e8d0790fc116fb6a  # frozen: v1.3.1
    hooks:
      - id: autoflake
        require_serial: true
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        language_version: python3
        require_serial: true
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [--config=setup.cfg]
