language: generic

os: linux

# default mysql on xenial will by 5.7
dist: xenial

env:
  global:
    - MYSQL_HOST=127.0.0.1
    - MYSQL_USER=root
    - MYSQL_DB=bgm_ip_viewer
    - REDIS_HOST=127.0.0.1
    - PIPENV_SYSTEM=1

cache:
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
    - /opt/pyenv
    - /opt/pyenv/versions/3.7.3

services:
  - mysql
  - redis-server

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - >-
    mysql -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DB
    DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;"
  - wget https://se4.trim21.cn/ci/data/personal-website/tests_data/relation.sql
  - wget https://se4.trim21.cn/ci/data/personal-website/tests_data/subject.sql
  - wget https://se4.trim21.cn/ci/data/personal-website/tests_data/tag.sql
  - mysql --database=$MYSQL_DB < ./subject.sql
  - mysql --database=$MYSQL_DB < ./relation.sql
  - mysql --database=$MYSQL_DB < ./tag.sql
  - bash scripts/install_python_with_pyenv.sh
  - pip install -U pip pipenv codecov

install:
  - pipenv install --system --deploy --dev

script:
  - pre-commit run --all-files
  - PYTHONPATH=$PWD coverage run -m pytest
  - docker build -t api-server -f Dockerfile .
  - docker build -t spider -f Dockerfile.spider .

after_success:
  - codecov
