[tool.poetry]
name = "personal-website"
version = "0.1.0"
description = ""
authors = ["Trim21 <i@trim21.me>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22.0"
requests-async = "^0.6.2"
peewee = "^3.10"
msgpack = "^0.6.1"
apscheduler = "^3.6.1"
scrapy-redis = "^0.6.8"
tqdm = "^4.35"
scrapy = "^1.7"
lxml = "^4.4"
loguru = "^0.3.2"
pytz = "^2019.2"
better_exceptions = "^0.2.2"
email-validator = "^1.0.4"
jinja2 = "^2.10.1"
icalendar = "^4.0.3"
mistune = "^0.8.4"
peewee-async = "^0.6.3a0"
aioredis = "^1.2.0"
python-dateutil = "^2.8.0"
sentry-sdk = "^0.11.1"
uvicorn = "^0.8.6"
gunicorn = "^19.9.0"
fastapi = "^0.36.0"
python-multipart = "^0.0.5"
cython = "^0.29.13"
aiomysql = "^0.0.20"
celery = {version = "^4.3", extras = ["redis"]}
sphinx-rtd-theme = {version = "^0.4.3", optional = true}
sphinx = {version = "^2.2", optional = true}
gitpython = {version = "^3.0.2", optional = true}
sphinxcontrib-openapi = {version = "^0.4.0", optional = true}
sphinxcontrib-httpexample = {version = "^0.10.3", optional = true}
sphinxcontrib-httpdomain = {version = "^1.7", optional = true}
sphinx-issues = {version = "^1.2", optional = true}



[tool.poetry.dev-dependencies]
pytest = "^5.1.1"
pytest-mock = "^1.10.4"

mock = "^3.0.5"
pre-commit = "^1.18.2"
yapf = "^0.28.0"
autoflake = "^1.3"
isort = "^4.3.21"
pyupgrade = "^1.22.1"
flake8-comprehensions = "^2.2.0"
flake8-bugbear = "^19.8.0"
flake8-commas = "^2.0.0"
flake8-mutable = "^1.2.0"
livereload = "^2.6.1"
gevent = "^1.4"
asynctest = "^0.13.0"
codecov = "^2.0"

[tool.poetry.extras]
docs = [
"sphinx",
"sphinx-rtd-theme",
"sphinxcontrib-httpdomain",
"sphinxcontrib-httpexample",
"sphinxcontrib-openapi",
"sphinx-issues",
"gitpython"
]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
