version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout # check out the code in the project directory

      - restore_cache:
          keys:
            - pip-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}-{{ checksum ".pre-commit-config.yaml" }}
            - pip-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-v2-{{ .Branch }}-
            - pip-v2-

      - run: pip install pipenv -U
      - run: |
          python --version
          pip --version # run the `echo` command
          pipenv --version

      - run:
          name: install dependencies
          command: sudo pipenv install --system --deploy --dev

      - run:
          name: code style
          command: pre-commit run --all-files

      - save_cache:
          key: pip-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - /home/circleci/.cache/pip
            - /home/circleci/.cache/pre-commit
