jobs:
- job: 'Docs'
  pool:
    vmImage: $(vm_image)

  steps:
    - template: /.ci/templates/steps/install-project.yaml

    - script: make html
      displayName: Build Docs
      workingDirectory: ./docs

    - publish: $(System.DefaultWorkingDirectory)/docs/build/html
      artifact: docs
