---
version: 1
update_configs:
- commit_message:
    prefix: chore
    include_scope: true
  directory: "/"
  package_manager: python
  target_branch: dev
  update_schedule: weekly
- commit_message:
    prefix: chore
    include_scope: true
  directory: "/.docker"
  package_manager: docker
  target_branch: dev
  update_schedule: weekly
- commit_message:
    prefix: chore
    include_scope: true
  directory: "/"
  package_manager: submodules
  target_branch: dev
  update_schedule: weekly
