name: check pre-commit update

on:
  push:
    branches:
      - dev
  schedule:
    # monthly on github default branch
    - cron:  '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Checkout branch
        run: git checkout "${GITHUB_REF:11}"

      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Get Latest tools version
        id: get-version
        run: |
          echo "::set-output name=poetry::$(curl -sSl https://pypi.org/pypi/poetry/json | jq .info.version -r)"
          echo "::set-output name=python::$(python -V)"

      - uses: actions/cache@v1
        with:
          path: ~/.poetry
          key: ${{ steps.get-version.outputs.poetry }}

      - name: Install Poetry
        run: |
          echo "::add-path::$HOME/.local/bin"
          echo "::add-path::$HOME/.poetry/bin"
          $HOME/.poetry/bin/poetry --version && exit 0
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --version 1.0.1
#          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --version ${{ steps.get-version.outputs.poetry }}

      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.local
          key: ${{ steps.get-version.outputs.python }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: |
          pip install --no-deps -q -r <(poetry export -f requirements.txt --dev)
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: 'false'
          PIP_USER: '1'

      - name: check if pre-commit update
        run: pre-commit autoupdate && git diff --exit-code

      - name: Create A PR
        if: failure()
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update pre-commit config'
          title: 'chore: update pre-commit config'
          author: 'Trim21[bot] <github@trim21.me>'
          branch: create-pull-request/pre-commit
